version: '3'
services:
  crc-calc:
    build:
      context: "./crc-calc"
    environment:
      - "DEBUG=true"
    networks:
      - "go-tx"
    ports:
      - "80:8080"
    tty: true

  byte-composer:
    build:
      context: "./byte-composer"
    environment:
      - "DEBUG=true"
      - "CRC_CALC_HOST=crc-calc"
      - "CRC_CALC_PORT=8080"
    networks:
      - "go-tx"
    ports:
      - "81:8080"
    tty: true

networks:
  go-tx:
