version: '3'
services:
  crc-calc:
    build:
      context: "./crc-calc"
      dockerfile: ".Dockerfile"
    env_file:
      - "./crc-calc/.env-dev"
    command: "bash -c 'go build -v . && ./crc-calc'"
    volumes:
      - "./crc-calc:/go/src/github.com/morfeush22/go-tx/crc-calc"
    environment:
      - "DEBUG=true"
    networks:
      - "go-tx"
    ports:
      - "80:8080"
    tty: true

  byte-composer:
    build:
      context: "./byte-composer"
      dockerfile: ".Dockerfile"
    env_file:
      - "./byte-composer/.env-dev"
    command: "bash -c 'go build -v . && ./byte-composer'"
    volumes:
      - "./byte-composer:/go/src/github.com/morfeush22/go-tx/byte-composer"
    environment:
      - "DEBUG=true"
    networks:
      - "go-tx"
    ports:
      - "81:8080"
    tty: true

networks:
  go-tx:
