version: '3'
services:
  crc-calc:
    build:
      context: "./crc-calc"
      dockerfile: ".Dockerfile"
    command: "bash -c 'go build -v . && ./crc-calc'"
    volumes:
      - "./crc-calc:/go/src/github.com/morfeush22/go-tx/crc-calc"
      - "logging:/logging"
    environment:
      - "DEBUG=true"
    env_file:
      - "./crc-calc/.env"
    networks:
      - "go-tx"
    ports:
      - "80:8080"
    tty: true
    depends_on:
      - queue
      - filebeat

  modulator:
    build:
      context: "./modulator"
      dockerfile: ".Dockerfile"
    command: "bash -c 'go build -v . && ./modulator'"
    volumes:
      - "./modulator:/go/src/github.com/morfeush22/go-tx/modulator"
      - "logging:/logging"
    environment:
      - "DEBUG=true"
    env_file:
      - "./modulator/.env"
    networks:
      - "go-tx"
    ports:
      - "81:8080"
    tty: true
    depends_on:
      - queue
      - filebeat

  queue:
    image: "rabbitmq:alpine"
    networks:
      - "go-tx"
    ports:
      - "5672:5672"

  filebeat:
    image: "docker.elastic.co/beats/filebeat:6.3.0"
    networks:
      - "go-tx"
    volumes:
      - "./logging/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "logging:/logging"

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.0"
    networks:
      - "go-tx"

  logstash:
    image: "docker.elastic.co/logstash/logstash-oss:6.3.0"
    networks:
      - "go-tx"
    volumes:
      - "./logging/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"

  kibana:
    image: "docker.elastic.co/kibana/kibana-oss:6.3.0"
    networks:
      - "go-tx"
    ports:
      - "5601:5601"

networks:
  go-tx:

volumes:
  logging:
